### PR TITLE
Fixes an issue caused by accessing undefined observable

### PR DESCRIPTION
**Pull request by garymjr**
I was having similar issues as seen in issue #5 so I started looking at the code. It looks like it was checking to see if an observable was an action and this caused an error if the observable was undefined or null. I put in a check to make sure the observable returned a value before checking to see if it's an action.

### CODE REVIEW

**Comment by Raathigesh** [comment]
This is awesome. Thank you so much.

**Comment by garymjr** [comment]
@Raathigesh Thanks for merging! I appreciate the work put into the UI of that app. Can you let me know when this will be live on npm? Thanks!

**Comment by Raathigesh** [comment]
Thank you. Thank you for reminding. Sorry i forgot to push a release. I'll
do it in another 12 hours. Cheers.

**Comment by Raathigesh** [comment]
Released with mobx-wiretap@0.13.1. Please let me know if you run into any issues.

**Pull request merged**
